src/home/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from .views import *

app_name = "home_app"

urlpatterns = [
    path("", HomeView.as_view(), name="home_page"),
    path("help", HelpView.as_view(), name="help"),
]

src/jobboard/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("home.urls")),
    path("", include("config.urls")),
    path("offer/", include("offers.urls")),
    path("reports/", include("reports.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/offers/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from .views import *

app_name = "offers_app"

urlpatterns = [
    # OFFERS
    path("list", OfferList.as_view(), name="offer_list"),
    path("panel", BiddingPanel.as_view(), name="bidding_panel"),
    path("publish", PublicationCreate.as_view(), name="offer_add"),
    path("update/<slug:slug>", PublicationEdit.as_view(), name="offer_edit"),
    path("detail/<slug:slug>", OfferDetail.as_view(), name="offer_detail"),
    path("modal/create", OfferModalCreate.as_view(), name="offer_modal_add"),
    path("modal/edit/<int:pk>", OfferEditModal.as_view(), name="offer_edit"),
    path("modal/delete/<slug:slug>", OfferDeleteModal.as_view(), name="offer_delete"),
    path("modal/finish/<slug:slug>", OfferFinishModal.as_view(), name="offer_finish"),
    path(
        "<str:username>/publications", PublicationList.as_view(), name="mypublications"
    ),
    # CANDIDATURES
    path("candidatures/list", CandidaturesList.as_view(), name="candidature_list"),
    path(
        "<slug:slug>/candidatures/list",
        CandidaturesByOfferList.as_view(),
        name="candidature_list",
    ),
    path(
        "candidatures/<str:username>/list",
        MyCandidacies.as_view(),
        name="mycandidacies",
    ),
    path(
        "<str:slug>/candidatures/save/<str:username>",
        CandidatureStatusEdit.as_view(),
        name="candidature_status_edit",
    ),
    path(
        "candidatures/modal/edit/<int:pk>",
        CandidatureEditModal.as_view(),
        name="candidature_edit",
    ),
    path(
        "candidatures/modal/delete/<int:pk>",
        CandidatureDeleteModal.as_view(),
        name="candidature_delete",
    ),
]

src/users/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from .views import *

app_name = "users_app"

urlpatterns = [
    # USER GROUPS
    path("user/group/list", UserGroupList.as_view(), name="usergroup_list"),
    path("user/group/add", UserGroupCreate.as_view(), name="usergroup_add"),
    path(
        "user/group/edit/<int:pk>",
        UserGroupEditModal.as_view(),
        name="usergroup_edit",
    ),
    path(
        "user/group/delete/<int:pk>",
        UserGroupDeleteModal.as_view(),
        name="usergroup_delete",
    ),
    # RESTRICTIONS
    path(
        "user/restriction/list",
        RestrictionList.as_view(),
        name="restriction_list",
    ),
    path(
        "user/restriction/add",
        RestrictionCreate.as_view(),
        name="restriction_add",
    ),
    path(
        "user/restriction/edit/<int:pk>",
        RestrictionEditModal.as_view(),
        name="restriction_edit",
    ),
    path(
        "user/restriction/delete/<int:pk>",
        RestrictionDeleteModal.as_view(),
        name="restriction_delete",
    ),
    # APPS
    path("user/app/list", AppList.as_view(), name="app_list"),
    path(
        "user/app/edit/<int:pk>",
        AppEditModal.as_view(),
        name="app_edit",
    ),
    # ROLES
    path("user/role/list", RoleList.as_view(), name="role_list"),
    path("user/role/add", RoleCreate.as_view(), name="role_add"),
    path("user/role/edit/<int:pk>", RoleEditModal.as_view(), name="role_edit"),
    path(
        "user/role/delete/<int:pk>",
        RoleDeleteModal.as_view(),
        name="role_delete",
    ),
    # POLICY
    path("user/policy/list", PolicyList.as_view(), name="policy_list"),
    path("user/policy/add", PolicyCreate.as_view(), name="policy_add"),
    path("user/policy/edit/<int:pk>", PolicyEditModal.as_view(), name="policy_edit"),
    path(
        "user/policy/delete/<int:pk>",
        PolicyDeleteModal.as_view(),
        name="policy_delete",
    ),
    # USER RULES
    path("user/rule/list", UserRulesList.as_view(), name="rule_list"),
    path("user/rule/add", UserRulesCreate.as_view(), name="rule_add"),
    path("user/rule/edit/<int:pk>", UserRulesEditModal.as_view(), name="rule_edit"),
    path(
        "user/rule/delete/<int:pk>",
        UserRulesDeleteModal.as_view(),
        name="rule_delete",
    ),
    # USERS
    path("user/list", UserList.as_view(), name="user_list"),
    path("user/add", UserCreate.as_view(), name="user_add"),
    path("user/edit/<int:pk>", UserEditModal.as_view(), name="user_edit"),
    path("user/delete/<int:pk>", UserDeleteModal.as_view(), name="user_delete"),
    # LOG
    path("login/", UserLogin.as_view(), name="login"),
    path("logout", UserLogout.as_view(), name="logout"),
    # path("register", RegisterView.as_view(), name="register"),
    path("register/choices", PreRegisterView.as_view(), name="register_choices"),
    path("register/student", RegisterStudentView.as_view(), name="register_student"),
    path("register/company", RegisterCompanyView.as_view(), name="register_company"),
    # path(
    #     "user/retrieve/credentials",
    #     RetrieveCredentials.as_view(),
    #     name="retrieve_credentials",
    # ),
    path(
        "user/<slug:slug>/password/recovery",
        PasswordRecovery.as_view(),
        name="password_recovery",
    ),
    # USER PROFILE
    path("profile/<slug:slug>", UserProfileDetail.as_view(), name="userprofile"),
    path(
        "profile/<slug:slug>/add",
        UserProfileCreate.as_view(),
        name="userprofile_add",
    ),
    path(
        "profile/<slug:slug>/edit",
        UserProfileEdit.as_view(),
        name="userprofile_edit",
    ),
    # CURRICULUM VITAE
    path(
        "curriculum/<slug:slug>/add",
        CurriculumVitaeCreate.as_view(),
        name="cv_add",
    ),
    path(
        "curriculum/<slug:slug>/edit",
        CurriculumVitaeEdit.as_view(),
        name="cv_edit",
    ),
    path(
        "curriculum/<slug:slug>/delete/attached",
        CurriculumVitaeDeleteAttached.as_view(),
        name="cv_delete_attached",
    ),
    path(
        "curriculum/<slug:slug>/attach",
        CurriculumVitaeAttach.as_view(),
        name="cv_attach",
    ),
    # NOTIFICATIONS
    path(
        "<str:username>/notifications", NotificationList.as_view(), name="notifications"
    ),
]

src/offers/models.py
from django.db import models

from config.models import Countries, Currencies, Cities, DocumentType

from django.utils.translation import gettext_lazy as _

from django.contrib.auth.models import User, AbstractUser
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.core.mail import send_mail
from django.template.defaultfilters import slugify

from .utils import string_to_base64, POST_STATUS, OFFER_STATUS
from .managers import OffersManager
from config.models import *


# Create your models here.
class Tags(models.Model):
    name = models.CharField(_("name"), max_length=15, unique=True, null=False)

    def __str__(self):
        return "{}".format(self.name)

    def slug(self):
        return slugify(self.name)

    class Meta:
        verbose_name = _("tag")
        verbose_name_plural = _("tags")


class Requirements(models.Model):
    name = models.CharField(_("name"), max_length=50, null=False)

    def __str__(self):
        return "{}".format(self.name)

    def slug(self):
        return slugify(self.name)

    class Meta:
        verbose_name = _("requirement")
        verbose_name_plural = _("requirements")


class Offers(models.Model):
    user = models.ForeignKey(
        User,
        related_name="offer_user",
        verbose_name=_("user"),
        blank=False,
        on_delete=models.PROTECT,
    )
    status = models.BooleanField(_("finish status"), default=False)
    slug = models.SlugField(max_length=255, unique=True)
    title = models.CharField(_("title"), max_length=255, null=False)
    salary = models.DecimalField(
        _("salary"), max_digits=10, decimal_places=2, blank=False, null=False
    )
    currency = models.ForeignKey(
        Currencies,
        related_name="offer_currency",
        verbose_name=_("currency"),
        blank=False,
        on_delete=models.PROTECT,
    )
    vacancies = models.IntegerField(default=0, blank=True, null=True)
    modality = models.ForeignKey(
        Modalities,
        related_name="offer_modality",
        verbose_name=_("modality"),
        blank=False,
        on_delete=models.PROTECT,
    )
    city = models.ForeignKey(
        Cities,
        related_name="offer_city",
        verbose_name=_("city"),
        blank=False,
        on_delete=models.PROTECT,
    )
    hiring_date = models.DateField(auto_now_add=False, editable=True, null=True)
    conttype = models.ForeignKey(
        ContractTypes,
        related_name="offer_contract_type",
        verbose_name=_("contract type"),
        blank=True,
        null=True,
        on_delete=models.PROTECT,
    )
    workday = models.ForeignKey(
        Workdays,
        related_name="offer_workday",
        verbose_name=_("workday"),
        blank=True,
        null=True,
        on_delete=models.PROTECT,
    )
    payperiod = models.ForeignKey(
        PayPeriods,
        related_name="offer_payperiod",
        verbose_name=_("pay period"),
        blank=True,
        null=True,
        on_delete=models.PROTECT,
    )
    description = models.TextField(_("description"), null=False)
    requirements = models.ManyToManyField(
        Requirements,
        related_name="offers_requirements",
        verbose_name=_("requirements"),
        blank=True,
    )
    tags = models.ManyToManyField(
        Tags,
        related_name="offers_tags",
        verbose_name=_("tags"),
        blank=True,
    )
    created_at = models.DateTimeField(_("created at"), auto_now_add=True, null=False)
    updated_at = models.DateTimeField(
        _("updated at"), auto_now_add=False, editable=True, null=True
    )
    deleted_at = models.DateTimeField(
        _("deleted at"), auto_now_add=False, editable=True, null=True
    )

    objects = OffersManager()

    def __str__(self):
        return "{}".format(self.title)

    def slug(self):
        _b = self.pk
        _field = f"{self.title} {_b}"
        return slugify(_field)

    def get_requirements(self):
        if self.requirements:
            return self.requirements.all()

    def get_tags(self):
        if self.tags:
            return self.tags.all()

    class Meta:
        verbose_name = _("offer")
        verbose_name_plural = _("offers")


class Candidatures(models.Model):
    offer = models.ForeignKey(
        Offers,
        related_name="candidature_offer",
        verbose_name=_("offer"),
        blank=False,
        on_delete=models.PROTECT,
    )
    status = models.CharField(
        _("candidature status"), max_length=2, null=False, choices=POST_STATUS
    )
    candidate = models.ForeignKey(
        User,
        related_name="candidate",
        verbose_name=_("candidate"),
        blank=False,
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(_("created at"), auto_now_add=True, null=False)
    updated_at = models.DateTimeField(
        _("updated at"), auto_now_add=False, editable=True, null=True
    )
    deleted_at = models.DateTimeField(
        _("deleted at"), auto_now_add=False, editable=True, null=True
    )

    def __str__(self):
        return "{}".format(self.candidate.username)

    class Meta:
        verbose_name = _("candidature")
        verbose_name_plural = _("candidatures")

src/users/templates/partials/_candidature_notification.html
{% load static %} {% load format_numbers %}

<div class="card bid-letter position-relative">
  <div class="card-body m-0">
    <h6 class="">{{ row.target.offer.title }}</h6>
    <div class="card-text">
      <div class="col-12 mb-2">
        <div class="text-truncate">{{ row.target.offer.description }}</div>
      </div>
      <div class="col-12 d-flex gap-2">
        {% include 'partials/icon_element/_dolar_icon.html' %}
        <span class="text-black">
          {{ row.target.offer.currency }}
          {{ row.target.offer.salary|currency_format }}
          {{ row.target.offer.payperiod }}
        </span>
      </div>
      <a
        href="{% url 'offers_app:offer_detail' row.target.offer.slug %}"
        class="stretched-link"
        role="button"
      ></a>
    </div>
  </div>
</div>

src/users/templates/partials/_company_profile.html
<div class="row gap-4 col-md-6">
    <div class="card col-12">
      <div class="card-body">
        <div class="row row-gap-2">
          <h5 class="fw-bold m-0 col-12 mb-3">Información corporativa</h5>
          <div class="col-md-6 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">
                RAZÓN SOCIAL
              </p>
              <p class="col-12 m-0">
                {% if object.userprofile.company_profile.name %} 
                {{ object.userprofile.company_profile.name }}
                {% else %}
                ------
                {% endif %}
              </p>
            </div>
          </div>
          <div class="col-md-6 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">
                {{ object.userprofile.document_type }}
              </p>
              <p class="col-12 m-0">
                {% if object.userprofile.id_number %} 
                {{ object.userprofile.id_number }}
                {% else %}
                ------
                {% endif %}
              </p>
            </div>
          </div>
          {% if object.userprofile.company_profile.personnel.all %} 
          {% for personnel in object.userprofile.company_profile.personnel.all %}
          <div class="col-md-6 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">
                {{ personnel.specialization.name }}
              </p>
              <p class="col-12 m-0">
                {{ personnel.fullname }}
              </p>
            </div>
          </div>
          <div class="col-md-6 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">
                {{ personnel.document_type.name }}
              </p>
              <p class="col-12 m-0">
                {{ personnel.id_number }}
              </p>
            </div>
          </div>
          {% endfor %}
          {% endif %}
          
        </div>
      </div>
    </div>
  </div>

src/users/templates/partials/_cv_profile.html
{% load tz %}

<div class="row gap-4 {% if object.userprofile.user_cv %}col-md-6{% else %}col-md-4{% endif %}">
  <div class="card col-12">
    <div class="card-body">
      <div class="row row-gap-2">
        {% if object.userprofile.user_cv %}
          <div class="d-flex justify-content-between align-items-center">
            <h5 class="fw-bold m-0 mb-3">Hoja de vida</h5>
            {% if request.user.is_staff or request.user.username == object.username %}
            <a role="button" class="btn btn-primary" href="{% url 'users_app:cv_edit' username %}">
              Editar
            </a>
            {% endif %}
          </div>
          {% if object.userprofile.user_cv.specialization.name %}
          <div class="col-md-12 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">Especialización</p>
              <p class="col-12 m-0">
                {{ object.userprofile.user_cv.specialization.name }}
              </p>
            </div>
          </div>
          {% endif %}
          {% if object.userprofile.user_cv.skills %}
          <div class="col-md-12 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">
                Conocimientos y/o Habilidades
              </p>
              <p class="col-12 m-0">
                {{ object.userprofile.user_cv.skills }}
              </p>
            </div>
          </div>
          {% endif %}
          {% if object.userprofile.user_cv.cv_works.all %}
          <div class="col-md-12 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">Experiencia laboral</p>
              {% for works in object.userprofile.user_cv.cv_works.all %}
              <p class="col-12 m-0">
                <strong>Empresa: </strong>
                {% if works.company.company %}
                {{ works.company.company.name }}
                {% else %}
                {{ works.company.another_name }}
                {% endif %}
                <br />
                <strong>Fecha: </strong>
                Desde {{ works.company.start_date }},
                hasta
                {% if works.company.currently %}
                la actualidad
                {% else %}
                {{ works.company.end_date }}
                {% endif %}
                <br />
                <strong>Funciones: </strong>
                {{ works.performances }}
                <br />
                <strong>Calificación: </strong>
                {{ works.rating }}
                <br />
              </p>
              {% empty %} 
              <p class="col-12 m-0">------</p>
              {% endfor %}
            </div>
          </div>
          {% endif %}
          {% if object.userprofile.user_cv.cv_education.all %}
          <div class="col-md-12 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">Estudios</p>
              {% for education in object.userprofile.user_cv.cv_education.all %}
              <p class="col-12 m-0">
                <strong>Institución: </strong>
                {{ education.academy.another_name }}
                <br />
                <strong>Nivel alcanzado: </strong>
                {{ education.get_level_display }}
                <br />
                <strong>Fecha: </strong>
                Desde {{ education.academy.start_date }},
                hasta
                {% if education.academy.currently %}
                la actualidad
                {% else %}
                {{ education.academy.end_date }}
                {% endif %}
                <br />
              </p>
              {% empty %} 
              <p class="col-12 m-0">------</p>
              {% endfor %}
            </div>
          </div>
          {% endif %}
          {% if object.userprofile.user_cv.cv_languages.all %}
          <div class="col-md-12 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">Idiomas</p>
              {% for perlan in object.userprofile.user_cv.cv_languages.all %}
              <p class="col-12 m-0">
                <strong>Idioma: </strong>
                {{ perlan.language.name }}
                <br />
                <strong>Nivel: </strong>
                {{ perlan.get_level_display }}
                <br />
              </p>
              {% empty %} 
              <p class="col-12 m-0">------</p>
              {% endfor %}
            </div>
          </div>
          {% endif %}
          <div class="col-md-12 mb-2">
            <div class="row">
              <p class="col-12 fw-semibold fst-italic mb-1">
                Hoja de vida adjunta
              </p>
              <div class="col-12 m-0">
                {% if object.userprofile.user_cv.attached %}
                <div class="d-flex gap-1">
                  <div class="pdf-thumbnail" style="width: fit-content;">
                    <div id="pdfThumbnail">
                      <div class="spinner-border" style="width: 2rem; height: 2rem;" role="status">
                        <span class="visually-hidden">Cargando hoja de vida...</span>
                      </div>
                      <span>Cargando hoja de vida...</span>
                    </div>
                    <div class="pdf-thumbnail-hover-hidden" id="pdfUpBtn" url="{{object.userprofile.user_cv.attached.url}}">
                      <span>
                        <i class="bi bi-eye"></i>
                      </span>
                    </div>
                  </div>
                  <button 
                    class="btn btn-sm m-0 p-1 d-flex justify-content-center align-items-center"
                    name="deleteButtons"
                    id="{% url 'users_app:cv_delete_attached' username %}"
                    style="height: fit-content; width: fit-content; font-size: 14px"
                  >
                    <i class="lni lni-close"></i>
                  </button>
                </div>
                {% else %}
                ------
                {% endif%}
              </div>
            </div>
          </div>
        {% else %}
          <h5 class="card-title">¿No tienes aún una hoja de vida?</h5>
          <div class="card-text mb-2">
            ¡Añade una rapidamente!
            <br>
            Las empresas la utilizan para conocerte y medir tus capacidades con respecto al cargo al que estás aplicando.
          </div>
          <div class="col-md-12">
            <div class="d-flex justify-content-evenly align-items-center">
              <a
                class="btn btn-primary"
                href="{% url 'users_app:cv_add' username %}"
              >
                <i class="lni lni-padlock"></i>
                <span class="">Crea la tuya</span>
              </a>
              o
              <button 
                class="btn btn-secondary"
                name="editButtons"
                id="{% url 'users_app:cv_attach' username %}"
              >
                <i class="lni lni-padlock"></i>
                <span class="">Adjunta una</span>
              </button>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

src/users/templates/partials/_offer_notification.html
{% load static %} {% load format_numbers %}

<div class="card bid-letter position-relative">
  <div class="card-body m-0">
    <h6 class="">{{ row.target.title }}</h6>
    <div class="card-text">
      <div class="col-12 mb-2">
        <div class="text-truncate">{{ row.target.description }}</div>
      </div>
      <div class="col-12 d-flex gap-2">
        {% include 'partials/icon_element/_dolar_icon.html' %}
        <span class="text-black">
          {{ row.target.currency }}
          {{ row.target.salary|currency_format }}
          {{ row.target.payperiod }}
        </span>
      </div>
      <a
        href="{% url 'offers_app:offer_detail' row.target.slug %}"
        class="stretched-link"
        role="button"
      ></a>
    </div>
  </div>
</div>

src/users/templates/partials/_picprofile.html
<picture class="img-content__info display-5" id="previewPic">
  {% if object.userprofile.avatar and object.userprofile.avatar.url %}
  <img
    src="{{ object.userprofile.avatar.url }}"
    alt="{{ object.user.username }}_pic"
    onerror="this.src = 'https://img.freepik.com/vector-gratis/plantilla-web-error-404-monstruo-divertido_23-2147788958.jpg?w=826&t=st=1682694445~exp=1682695045~hmac=6a60f264a5445d00221f109af77952c9c1e8f0b5b78544b5b6d868272f76ba8f';"
  />
  {% else %}
  <span class="bg-orange text-white letterpic text-uppercase">
    {{ username.0 }}
  </span>
  {% endif %}
</picture>

src/users/templates/partials/_public_profile_picture.html
<div 
  class="d-flex flex-column gap-1 align-items-center"
>
  {% comment %} {% if row.status == '5' %}bg-orange pb-3 rounded-top-circle{% endif %} {% endcomment %}
  <div 
    class="d-flex flex-column gap-1 align-items-center position-relative"
    style="border-radius: 0% 0% 20% 20%;"
  >
    <picture class="img-content__info display-5 position-relative bg-white" id="previewPic" style="z-index: 2;">
      {% if row.candidate.userprofile.avatar and row.candidate.userprofile.avatar.url %}
      <img
        src="{{ row.candidate.userprofile.avatar.url }}"
        alt="{{ row.candidate.user.username }}_pic"
        onerror="this.src = 'https://img.freepik.com/vector-gratis/plantilla-web-error-404-monstruo-divertido_23-2147788958.jpg?w=826&t=st=1682694445~exp=1682695045~hmac=6a60f264a5445d00221f109af77952c9c1e8f0b5b78544b5b6d868272f76ba8f';"
      />
      {% else %}
      <span class="bg-orange text-white letterpic text-uppercase">
        {{ row.candidate.username.0 }}
      </span>
      {% endif %}
      <a href="{% url 'users_app:userprofile' row.candidate.username %}" class="stretched-link hoverimage"></a>
    </picture>
    {% comment %} {% if row.status == '3' %}
    <div class="rounded-pill bg-secondary blind">
      <span>
        {{ row.get_status_display }}
      </span>
      <span style="font-size: 12px !important;">
        {{ row.updated_at.date|date:"d-M-Y" }}
      </span>
      <div>
        <i class="lni lni-warning"></i>
      </div>
    </div>
    {% endif %} {% endcomment %}
    {% comment %} {% if row.status == '5' %}
    <div class="rounded-pill bg-orange blind">
      <span>
        {{ row.get_status_display }}
      </span>
      <span style="font-size: 12px !important;">
        {{ row.updated_at.date|date:"d-M-Y" }}
      </span>
      <div>
        <i class="lni lni-briefcase"></i>
      </div>
    </div>
    {% endif %} {% endcomment %}
  </div>
  {% if row.status == '3' %}
  <div class="mt-2 d-flex flex-column gap-1 align-items-center">
    <i class="lni lni-sad"></i>
    <span>
      {{ row.get_status_display }}
    </span>
  </div>
  {% endif %}
  {% if row.status == '4' %}
  <div class="mt-2 d-flex flex-column gap-1 align-items-center">
    <i class="lni lni-checkmark"></i>
    <span>
      {{ row.get_status_display }}
    </span>
  </div>
  {% endif %}
  {% if row.status == '5' %}
  <div class="mt-2 d-flex flex-column gap-1 align-items-center">
    <i class="lni lni-briefcase"></i>
    <span>
      {{ row.get_status_display }}
    </span>
  </div>
  {% endif %}
</div>

src/users/templates/partials/_thumbnail.html
<picture
  class="rounded-circle fw-light img-thumbnail--custom"
  style="width: 2rem; height: 2rem"
>
  {% if request.user.userprofile and request.user.userprofile.avatar %}
  <img
    src="{{ request.user.userprofile.avatar.url }}"
    alt="{{ request.user.userprofile.user.username }}_pic"
    onerror="this.src = 'https://img.freepik.com/vector-gratis/plantilla-web-error-404-monstruo-divertido_23-2147788958.jpg?w=826&t=st=1682694445~exp=1682695045~hmac=6a60f264a5445d00221f109af77952c9c1e8f0b5b78544b5b6d868272f76ba8f';"
  />
  {% else %}
  <span class="bg-orange text-white letterpic text-uppercase">
    {{ request.user.username.0 }}
  </span>
  {% endif %}
</picture>

src/users/templates/partials/_uploadpic.html
<label for="uploadPic" class="overflow-hidden rounded-circle upload">
  <picture class="img-content__info display-5" id="previewPic">
    {% if object.avatar and object.avatar.url %}
    <img
      src="{{ object.avatar.url }}"
      alt="{{ object.user.username }}_pic"
      onerror="this.src = 'https://img.freepik.com/vector-gratis/plantilla-web-error-404-monstruo-divertido_23-2147788958.jpg?w=826&t=st=1682694445~exp=1682695045~hmac=6a60f264a5445d00221f109af77952c9c1e8f0b5b78544b5b6d868272f76ba8f';"
    />
    {% else %}
    <span class="bg-orange text-white letterpic text-uppercase">
      {{ username.0 }}
    </span>
    {% endif %}
  </picture>
</label>
<input class="form-control d-none" type="file" id="uploadPic" name="avatar" />

src/users/templates/partials/_user_aside.html
<div class="aside__container d-none d-lg-block">
  <div class="aside-content">
    <div class="sub-nav">
      <h5 class="m-0 sub-nav__title">Lorem Estudiante</h5>
      <div class="sub-nav__items">
        <ul class="m-0 p-0">
          <li>
            <a href="{% url 'users_app:userprofile' username %}">Perfil</a>
          </li>

          <li>
            <a href="">Postulaciones</a>
          </li>

          <li>
            <a href="/notifications">Notificaciones</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>