src/home/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from .views import *

app_name = "home_app"

urlpatterns = [
    path("", HomeView.as_view(), name="home_page"),
    path("help", HelpView.as_view(), name="help"),
]

src/jobboard/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("home.urls")),
    path("", include("config.urls")),
    path("offer/", include("offers.urls")),
    path("reports/", include("reports.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from .views import *

app_name = "users_app"

urlpatterns = [
    # USER GROUPS
    path("user/group/list", UserGroupList.as_view(), name="usergroup_list"),
    path("user/group/add", UserGroupCreate.as_view(), name="usergroup_add"),
    path(
        "user/group/edit/<int:pk>",
        UserGroupEditModal.as_view(),
        name="usergroup_edit",
    ),
    path(
        "user/group/delete/<int:pk>",
        UserGroupDeleteModal.as_view(),
        name="usergroup_delete",
    ),
    # RESTRICTIONS
    path(
        "user/restriction/list",
        RestrictionList.as_view(),
        name="restriction_list",
    ),
    path(
        "user/restriction/add",
        RestrictionCreate.as_view(),
        name="restriction_add",
    ),
    path(
        "user/restriction/edit/<int:pk>",
        RestrictionEditModal.as_view(),
        name="restriction_edit",
    ),
    path(
        "user/restriction/delete/<int:pk>",
        RestrictionDeleteModal.as_view(),
        name="restriction_delete",
    ),
    # APPS
    path("user/app/list", AppList.as_view(), name="app_list"),
    path(
        "user/app/edit/<int:pk>",
        AppEditModal.as_view(),
        name="app_edit",
    ),
    # ROLES
    path("user/role/list", RoleList.as_view(), name="role_list"),
    path("user/role/add", RoleCreate.as_view(), name="role_add"),
    path("user/role/edit/<int:pk>", RoleEditModal.as_view(), name="role_edit"),
    path(
        "user/role/delete/<int:pk>",
        RoleDeleteModal.as_view(),
        name="role_delete",
    ),
    # POLICY
    path("user/policy/list", PolicyList.as_view(), name="policy_list"),
    path("user/policy/add", PolicyCreate.as_view(), name="policy_add"),
    path("user/policy/edit/<int:pk>", PolicyEditModal.as_view(), name="policy_edit"),
    path(
        "user/policy/delete/<int:pk>",
        PolicyDeleteModal.as_view(),
        name="policy_delete",
    ),
    # USER RULES
    path("user/rule/list", UserRulesList.as_view(), name="rule_list"),
    path("user/rule/add", UserRulesCreate.as_view(), name="rule_add"),
    path("user/rule/edit/<int:pk>", UserRulesEditModal.as_view(), name="rule_edit"),
    path(
        "user/rule/delete/<int:pk>",
        UserRulesDeleteModal.as_view(),
        name="rule_delete",
    ),
    # USERS
    path("user/list", UserList.as_view(), name="user_list"),
    path("user/add", UserCreate.as_view(), name="user_add"),
    path("user/edit/<int:pk>", UserEditModal.as_view(), name="user_edit"),
    path("user/delete/<int:pk>", UserDeleteModal.as_view(), name="user_delete"),
    # LOG
    path("login/", UserLogin.as_view(), name="login"),
    path("logout", UserLogout.as_view(), name="logout"),
    # path("register", RegisterView.as_view(), name="register"),
    path("register/choices", PreRegisterView.as_view(), name="register_choices"),
    path("register/student", RegisterStudentView.as_view(), name="register_student"),
    path("register/company", RegisterCompanyView.as_view(), name="register_company"),
    # path(
    #     "user/retrieve/credentials",
    #     RetrieveCredentials.as_view(),
    #     name="retrieve_credentials",
    # ),
    path(
        "user/<slug:slug>/password/recovery",
        PasswordRecovery.as_view(),
        name="password_recovery",
    ),
    # USER PROFILE
    path("profile/<slug:slug>", UserProfileDetail.as_view(), name="userprofile"),
    path(
        "profile/<slug:slug>/add",
        UserProfileCreate.as_view(),
        name="userprofile_add",
    ),
    path(
        "profile/<slug:slug>/edit",
        UserProfileEdit.as_view(),
        name="userprofile_edit",
    ),
    # CURRICULUM VITAE
    path(
        "curriculum/<slug:slug>/add",
        CurriculumVitaeCreate.as_view(),
        name="cv_add",
    ),
    path(
        "curriculum/<slug:slug>/edit",
        CurriculumVitaeEdit.as_view(),
        name="cv_edit",
    ),
    path(
        "curriculum/<slug:slug>/delete/attached",
        CurriculumVitaeDeleteAttached.as_view(),
        name="cv_delete_attached",
    ),
    path(
        "curriculum/<slug:slug>/attach",
        CurriculumVitaeAttach.as_view(),
        name="cv_attach",
    ),
    # NOTIFICATIONS
    path(
        "<str:username>/notifications", NotificationList.as_view(), name="notifications"
    ),
]

src/users/views.py
# PYTHON MODULES
from datetime import datetime
import json

# DJANGO MODULES
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse_lazy, reverse, resolve
from django.views import generic
from django.db import IntegrityError
from django.conf import settings
from django.utils.timezone import now
from django.db.models import (
    Q,
    F,
    Count,
    CharField,
    DecimalField,
    Value,
    Sum,
    Avg,
    Min,
    Max,
)
from django.utils.translation import gettext as _

# EXTRA MODULES
import sweetify
from notifications.models import Notification

# PROJECT MODULES
from users.forms import *
from users.models import *
from core.utils import *
from core.middlewares import UserLoggedMixin
from users.utils import *
from jobboard.utils import *

# PROJECT FORMS

# GLOBAL VARIABLES
app_title = _("Usuarios")
usergroup_title = _("Grupos de usuarios")
usergroup_desc = _("Conjunto de usuarios que comparten un mismo propósito")
restriction_title = _("Restricciones")
restriction_desc = _("Todo tipo de acciones prohibidas para los usuarios")
app_view_title = _("Aplicaciones")
app_view_desc = _("Módulos del sistema")
role_title = _("Roles")
role_desc = _("Función que un usuario desempeña dentro del sistema")
policy_title = _("Regulaciones")
policy_desc = _("Normativas de ejecución para grupos de usuarios")
rule_title = _("Reglas")
rule_desc = _(
    "Directrices que categorizan usuarios y permiten y/o restringen sus movimientos dentro del sistema"
)
user_title = _("Usuarios")
user_desc = _("Usuarios del sistema")
userprofile_title = _("Perfiles de usuario")
userprofile_desc = _("Perfiles de usuario del sistema")
login_title = _("Ingresar")
login_desc = _("Inicio de sesión")
register_title = _("Registro")
register_desc = _("Registrarse")
register_choices_desc = _("Registrarse")
register_choices_title = _("Seleccion")
account_already = _("si ya dispone de Usuario y Contraseña")
student_register_desc = _("Registro Estudiantes")
company_register_desc = _("Registro Empresas")
recover_title = _("Recuperar Credenciales")
cv_title = _("Hoja de vida")
cv_desc = _("Llena tu hoja de vida para que las empresas puedan conocerte")

# Create your views here.


# USER GROUPS
class UserGroupList(LoginRequiredMixin, generic.ListView):
    login_url = "/login"
    model = UserGroups
    template_name = "usergroups/usergroup_list.html"
    paginate_by = 10

    def get_queryset(self):
        data = UserGroups.objects.all().order_by("id")
        return data

    def get_context_data(self, **kwargs):
        context = super(UserGroupList, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = usergroup_title
        context["description_view"] = usergroup_desc
        return context


class UserGroupCreate(LoginRequiredMixin, generic.CreateView):
    login_url = "/login"
    model = UserGroups
    form_class = UserGroupForm
    template_name = "usergroups/usergroup_create_modal.html"

    def get_success_url(self):
        success_message(self.request)
        return reverse_lazy("users_app:usergroup_list")

    def get_context_data(self, **kwargs):
        context = super(UserGroupCreate, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = usergroup_title
        context["description_view"] = usergroup_desc
        return context

    def form_valid(self, form):
        form.instance.code = str(form.instance.code).upper()
        form.instance.group_name = str(form.instance.group_name).lower()

        objects = duplicate_usergroups(self, form)
        if objects > 0:
            warning_message(self.request, msg="El registro ya existe")
            return HttpResponseRedirect(reverse_lazy("users_app:usergroup_list"))
        return super().form_valid(form)

    def form_invalid(self, form, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx["form"] = form

        msg_error = get_form_errors(form)
        warning_message(self.request, msg=msg_error)
        return HttpResponseRedirect(reverse_lazy("users_app:usergroup_list"))


class UserGroupEditModal(LoginRequiredMixin, generic.UpdateView):
    login_url = "/login"
    model = UserGroups
    form_class = UserGroupForm
    template_name = "usergroups/usergroup_update_modal.html"

    def get_success_url(self):
        success_message(self.request, msg="Registro actualizado satisfactoriamente")
        return reverse_lazy("users_app:usergroup_list")

    def get_context_data(self, **kwargs):
        context = super(UserGroupEditModal, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = usergroup_title
        context["description_view"] = usergroup_desc
        return context

    def form_valid(self, form):
        form.instance.code = str(form.instance.code).upper()
        form.instance.group_name = str(form.instance.group_name).lower()
        form.instance.updated_at = timezone.now()

        objects = duplicate_usergroups(self, form)
        if objects > 0:
            warning_message(self.request, msg="El registro ya existe")
            return HttpResponseRedirect(reverse_lazy("users_app:usergroup_list"))

        return super().form_valid(form)

    def form_invalid(self, form, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx["form"] = form

        msg_error = get_form_errors(form)
        warning_message(self.request, msg=msg_error)
        return self.render_to_response(ctx)


class UserGroupDeleteModal(LoginRequiredMixin, generic.UpdateView):
    login_url = "/login"
    model = UserGroups
    form_class = FormDelete
    template_name = "usergroups/usergroup_delete_modal.html"

    def get_success_url(self):
        success_message(self.request, msg="Registro eliminado satisfactoriamente")
        return reverse_lazy("users_app:usergroup_list")

    def get_context_data(self, **kwargs):
        context = super(UserGroupDeleteModal, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = usergroup_title
        context["description_view"] = usergroup_desc
        return context

    def form_valid(self, form):
        form.instance.deleted_at = timezone.now()
        return super().form_valid(form)


# RESTRICTIONS
class RestrictionList(LoginRequiredMixin, generic.ListView):
    login_url = "/login"
    model = Restrictions
    template_name = "restrictions/restriction_list.html"
    paginate_by = 10

    def get_queryset(self):
        data = Restrictions.objects.all().order_by("id")
        return data

    def get_context_data(self, **kwargs):
        context = super(RestrictionList, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = restriction_title
        context["description_view"] = restriction_desc
        return context


class RestrictionCreate(LoginRequiredMixin, generic.CreateView):
    login_url = "/login"
    model = Restrictions
    form_class = RestrictionForm
    template_name = "restrictions/restriction_create_modal.html"

    def get_success_url(self):
        success_message(self.request)
        return reverse_lazy("users_app:restriction_list")

    def get_context_data(self, **kwargs):
        context = super(RestrictionCreate, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = restriction_title
        context["description_view"] = restriction_desc
        return context

    def form_valid(self, form):
        form.instance.code = str(form.instance.code).upper()
        form.instance.name = str(form.instance.name).lower()

        count = duplicate_restrictions(self, form)
        if count > 0:
            warning_message(self.request, msg="El registro ya existe")
            return HttpResponseRedirect(reverse_lazy("users_app:restriction_list"))
        return super().form_valid(form)

    def form_invalid(self, form, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx["form"] = form

        msg_error = get_form_errors(form)
        warning_message(self.request, msg=msg_error)
        return HttpResponseRedirect(reverse_lazy("users_app:restriction_list"))


class RestrictionEditModal(LoginRequiredMixin, generic.UpdateView):
    login_url = "/login"
    model = Restrictions
    form_class = RestrictionForm
    template_name = "restrictions/restriction_update_modal.html"

    def get_success_url(self):
        success_message(self.request, msg="Registro actualizado satisfactoriamente")
        return reverse_lazy("users_app:restriction_list")

    def get_context_data(self, **kwargs):
        context = super(RestrictionEditModal, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = restriction_title
        context["description_view"] = restriction_desc
        return context

    def form_valid(self, form):
        count = duplicate_restrictions(self, form)
        form.instance.code = str(form.instance.code).upper()
        form.instance.name = str(form.instance.name).lower()
        form.instance.updated_at = timezone.now()

        if count > 0:
            warning_message(self.request, msg="El registro ya existe")
            return HttpResponseRedirect(reverse_lazy("users_app:restriction_list"))

        return super().form_valid(form)

    def form_invalid(self, form, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx["form"] = form

        msg_error = get_form_errors(form)
        warning_message(self.request, msg=msg_error)
        return HttpResponseRedirect(reverse_lazy("users_app:restriction_list"))

src/users/templates/userprofile/userprofile_add.html
{% extends 'core/base.html' %} {% load static %} 

{% block title %}
<title>{{app_title}} | {{title_view}}</title>
{% endblock title %}

{% block contentfluid %}

<section class="layout-section">
  {% include 'partials/_aside.html' %}
  <div class="row justify-content-start p-5 gap-3" style="width: calc(100% - 300px); margin-left: 300px;">
    <form method="POST" enctype="multipart/form-data" action="{% url 'users_app:userprofile_add' username %}" id="form">
      {% csrf_token %}
      {% include 'partials/_userprofile_form.html' %}
    </form>
  </div>
</section>
{% comment %} <article class="footer position-relative" style="z-index: 2;">
  {% include 'partials/_footer.html' %}
</article>  {% endcomment %}

{% endblock contentfluid %}

src/users/templates/userprofile/userprofile_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
<title>{{app_title}} | {{title_view}}</title>
{% endblock title %}

{% block contentfluid %}
<section class="layout-section">
  {% include 'partials/_aside.html' %}
  <div class="main-section">
    <div class="container">
      <div class="row justify-content-start gap-3">
        <h3 class="col-12">Perfil</h3>
        <div class="row gap-4 {% if object.userprofile.company_profile or object.userprofile.user_cv %}col-md-6{% else %}col-md-8{% endif %}">
          <div class="card col-12">
            <div class="card-body d-flex flex-row justify-content-between align-items-center flex-wrap gap-3">
              <div class="d-flex gap-4 justify-content-between align-items-center flex-wrap">
                {% include 'partials/_picprofile.html' %}
                <div class="d-flex flex-column gap-1 justify-content-center align-items-start">
                  <h5 class="fw-bold m-0">
                    {% if object.userprofile.company_profile.name %}
                    {{ object.userprofile.company_profile.name }}
                    {% elif object.first_name or object.last_name %}
                    {{object.first_name}} {{object.last_name}}
                    {% else %}
                    @{{ username }}
                    {% endif %}
                  </h5>
                  <p class="text-muted m-0 fw-light text-capitalize">
                    {% if object.is_superuser %}
                    Superusuario
                    {% elif object.is_staff %}
                    Staff
                    {% elif object.userprofile.user_cv.specialization %}
                    {{ object.userprofile.user_cv.specialization.name }}
                    {% else %}
                      {% for rule in object.rule_user.all %}
                      {{ rule.usergroup.group_name }}
                      {% endfor %}
                    {% endif %}
                    {% comment %} {% for rule in rules %}
                    {{ rule.usergroup.group_name }}
                    {% endfor %} {% endcomment %}
                  </p>
                </div>
              </div>
              <div class="">
                {% if request.user.is_staff or request.user.username == object.username %}
                {% if userprofile %}
                <a
                  class="btn btn-outline-primary btn-center"
                  href="{% url 'users_app:userprofile_edit' username %}"
                >
                  <i class="lni lni-pencil"></i>
                  <span class="ms-2">Editar</span>
                </a>
                {% else %}
                <a
                  class="btn btn-outline-primary btn-center data-info__btn--edit"
                  href="{% url 'users_app:userprofile_add' username %}"
                >
                  <i class="lni lni-pencil"></i>
                  <span class="ms-2">Editar</span>
                </a>
                {% endif %}
                {% endif %}
              </div>
              {% comment %} <button class="btn btn-outline-primary" type="button" style="height: fit-content;">Actualizar</button> {% endcomment %}
            </div>
          </div>
          <div class="card col-12">
            <div class="card-body">
              <div class="row row-gap-2">
                <h5 class="fw-bold m-0 col-12 mb-3">Información de usuario</h5>
                <div class="col-md-6 mb-2">
                  <div class="row">
                    <p class="col-12 fw-semibold fst-italic mb-1">
                      Usuario
                    </p>
                    <p class="col-12 m-0">
                      {% if object.username %}
                      @{{ object.username }}
                      {% else %}
                      {{ username }}
                      {% endif %}
                    </p>
                  </div>
                </div>
                <div class="col-md-6 mb-2">
                  <div class="row">
                    <p class="col-12 fw-semibold fst-italic mb-1">
                      Correo electrónico de registro
                    </p>
                    <p class="col-12 m-0">
                      {% if object.email %}
                      {{ object.email }}
                      {% else %}
                      ------
                      {% endif %}
                    </p>
                  </div>
                </div>
                {% if object.first_name %}
                <div class="col-md-6 mb-2">
                  <div class="row">
                    <p class="col-12 fw-semibold fst-italic mb-1">
                      Nombre(s)
                    </p>
                    <p class="col-12 m-0">
                      {{ object.first_name }}
                    </p>
                  </div>
                </div>
                {% endif %}
                {% if object.last_name %}
                <div class="col-md-6 mb-2">
                  <div class="row">
                    <p class="col-12 fw-semibold fst-italic mb-1">
                      Apellidos
                    </p>
                    <p class="col-12 m-0">
                      {{ object.last_name }}
                    </p>
                  </div>
                </div>
                {% endif %}
                <div class="col-md-12 mb-2">
                  <div class="row">
                    <p class="col-12 fw-semibold fst-italic mb-1">
                      Sobre mí
                    </p>
                    <p class="col-12 m-0">
                      {% if object.userprofile.about_me %}
                      {{ object.userprofile.about_me }}
                      {% else %}
                      ------
                      {% endif %}
                    </p>
                  </div>
                </div>
                {% if request.user.is_staff or request.user.username == object.username %}
                <div class="col-md-12 my-2">
                  <button
                    type="button"
                    class="btn btn-outline-primary btn-center btn-compact"
                    name="editButtons"
                    id="{% url 'users_app:password_recovery' username %}"
                  >
                    <i class="lni lni-padlock"></i>
                    <span class="">Cambiar contraseña</span>
                  </button>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        {% if request.user.is_staff or company %}
          {% include 'partials/_company_profile.html' %}
        {% endif %}
        {% if request.user.is_staff or graduate %}
        {% include 'partials/_cv_profile.html' %}
        {% endif %}
      </div>
    </div>
  </div>

</section>
{% comment %} <article class="footer position-relative" style="z-index: 2;">
  {% include 'partials/_footer.html' %}
</article>  {% endcomment %}

{% endblock contentfluid %}

src/users/templates/userprofile/userprofile_edit.html
{% extends 'core/base.html' %} {% load static %} 

{% block title %}
<title>{{app_title}} | {{title_view}}</title>
{% endblock title %}

{% block contentfluid %}

<section class="layout-section">
  {% include 'partials/_aside.html' %}
  <div class="main-section">
    <div class="container">
      <div class="row justify-content-start gap-3">
        <form method="POST" enctype="multipart/form-data" action="{% url 'users_app:userprofile_edit' username %}" id="form">
          {% csrf_token %}
          {% include 'partials/_userprofile_form.html' %}
        </form>
      </div>
    </div>
  </div>
</section>
{% comment %} <article class="footer position-relative" style="z-index: 2;">
  {% include 'partials/_footer.html' %}
</article>  {% endcomment %}

{% endblock contentfluid %}