src/home/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from .views import *

app_name = "home_app"

urlpatterns = [
    path("", HomeView.as_view(), name="home_page"),
    path("help", HelpView.as_view(), name="help"),
]

src/jobboard/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("home.urls")),
    path("", include("config.urls")),
    path("offer/", include("offers.urls")),
    path("reports/", include("reports.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/offers/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from .views import *

app_name = "offers_app"

urlpatterns = [
    # OFFERS
    path("list", OfferList.as_view(), name="offer_list"),
    path("panel", BiddingPanel.as_view(), name="bidding_panel"),
    path("publish", PublicationCreate.as_view(), name="offer_add"),
    path("update/<slug:slug>", PublicationEdit.as_view(), name="offer_edit"),
    path("detail/<slug:slug>", OfferDetail.as_view(), name="offer_detail"),
    path("modal/create", OfferModalCreate.as_view(), name="offer_modal_add"),
    path("modal/edit/<int:pk>", OfferEditModal.as_view(), name="offer_edit"),
    path("modal/delete/<slug:slug>", OfferDeleteModal.as_view(), name="offer_delete"),
    path("modal/finish/<slug:slug>", OfferFinishModal.as_view(), name="offer_finish"),
    path(
        "<str:username>/publications", PublicationList.as_view(), name="mypublications"
    ),
    # CANDIDATURES
    path("candidatures/list", CandidaturesList.as_view(), name="candidature_list"),
    path(
        "<slug:slug>/candidatures/list",
        CandidaturesByOfferList.as_view(),
        name="candidature_list",
    ),
    path(
        "candidatures/<str:username>/list",
        MyCandidacies.as_view(),
        name="mycandidacies",
    ),
    path(
        "<str:slug>/candidatures/save/<str:username>",
        CandidatureStatusEdit.as_view(),
        name="candidature_status_edit",
    ),
    path(
        "candidatures/modal/edit/<int:pk>",
        CandidatureEditModal.as_view(),
        name="candidature_edit",
    ),
    path(
        "candidatures/modal/delete/<int:pk>",
        CandidatureDeleteModal.as_view(),
        name="candidature_delete",
    ),
]

src/offers/models.py
from django.db import models

from config.models import Countries, Currencies, Cities, DocumentType

from django.utils.translation import gettext_lazy as _

from django.contrib.auth.models import User, AbstractUser
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.core.mail import send_mail
from django.template.defaultfilters import slugify

from .utils import string_to_base64, POST_STATUS, OFFER_STATUS
from .managers import OffersManager
from config.models import *


# Create your models here.
class Tags(models.Model):
    name = models.CharField(_("name"), max_length=15, unique=True, null=False)

    def __str__(self):
        return "{}".format(self.name)

    def slug(self):
        return slugify(self.name)

    class Meta:
        verbose_name = _("tag")
        verbose_name_plural = _("tags")


class Requirements(models.Model):
    name = models.CharField(_("name"), max_length=50, null=False)

    def __str__(self):
        return "{}".format(self.name)

    def slug(self):
        return slugify(self.name)

    class Meta:
        verbose_name = _("requirement")
        verbose_name_plural = _("requirements")


class Offers(models.Model):
    user = models.ForeignKey(
        User,
        related_name="offer_user",
        verbose_name=_("user"),
        blank=False,
        on_delete=models.PROTECT,
    )
    status = models.BooleanField(_("finish status"), default=False)
    slug = models.SlugField(max_length=255, unique=True)
    title = models.CharField(_("title"), max_length=255, null=False)
    salary = models.DecimalField(
        _("salary"), max_digits=10, decimal_places=2, blank=False, null=False
    )
    currency = models.ForeignKey(
        Currencies,
        related_name="offer_currency",
        verbose_name=_("currency"),
        blank=False,
        on_delete=models.PROTECT,
    )
    vacancies = models.IntegerField(default=0, blank=True, null=True)
    modality = models.ForeignKey(
        Modalities,
        related_name="offer_modality",
        verbose_name=_("modality"),
        blank=False,
        on_delete=models.PROTECT,
    )
    city = models.ForeignKey(
        Cities,
        related_name="offer_city",
        verbose_name=_("city"),
        blank=False,
        on_delete=models.PROTECT,
    )
    hiring_date = models.DateField(auto_now_add=False, editable=True, null=True)
    conttype = models.ForeignKey(
        ContractTypes,
        related_name="offer_contract_type",
        verbose_name=_("contract type"),
        blank=True,
        null=True,
        on_delete=models.PROTECT,
    )
    workday = models.ForeignKey(
        Workdays,
        related_name="offer_workday",
        verbose_name=_("workday"),
        blank=True,
        null=True,
        on_delete=models.PROTECT,
    )
    payperiod = models.ForeignKey(
        PayPeriods,
        related_name="offer_payperiod",
        verbose_name=_("pay period"),
        blank=True,
        null=True,
        on_delete=models.PROTECT,
    )
    description = models.TextField(_("description"), null=False)
    requirements = models.ManyToManyField(
        Requirements,
        related_name="offers_requirements",
        verbose_name=_("requirements"),
        blank=True,
    )
    tags = models.ManyToManyField(
        Tags,
        related_name="offers_tags",
        verbose_name=_("tags"),
        blank=True,
    )
    created_at = models.DateTimeField(_("created at"), auto_now_add=True, null=False)
    updated_at = models.DateTimeField(
        _("updated at"), auto_now_add=False, editable=True, null=True
    )
    deleted_at = models.DateTimeField(
        _("deleted at"), auto_now_add=False, editable=True, null=True
    )

    objects = OffersManager()

    def __str__(self):
        return "{}".format(self.title)

    def slug(self):
        _b = self.pk
        _field = f"{self.title} {_b}"
        return slugify(_field)

    def get_requirements(self):
        if self.requirements:
            return self.requirements.all()

    def get_tags(self):
        if self.tags:
            return self.tags.all()

    class Meta:
        verbose_name = _("offer")
        verbose_name_plural = _("offers")


class Candidatures(models.Model):
    offer = models.ForeignKey(
        Offers,
        related_name="candidature_offer",
        verbose_name=_("offer"),
        blank=False,
        on_delete=models.PROTECT,
    )
    status = models.CharField(
        _("candidature status"), max_length=2, null=False, choices=POST_STATUS
    )
    candidate = models.ForeignKey(
        User,
        related_name="candidate",
        verbose_name=_("candidate"),
        blank=False,
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(_("created at"), auto_now_add=True, null=False)
    updated_at = models.DateTimeField(
        _("updated at"), auto_now_add=False, editable=True, null=True
    )
    deleted_at = models.DateTimeField(
        _("deleted at"), auto_now_add=False, editable=True, null=True
    )

    def __str__(self):
        return "{}".format(self.candidate.username)

    class Meta:
        verbose_name = _("candidature")
        verbose_name_plural = _("candidatures")

src/offers/views.py
# PYTHON MODULES
from datetime import datetime
import json

# DJANGO MODULES
from django.contrib.auth.models import User
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse_lazy, reverse, resolve
from django.views import generic
from django.db import IntegrityError
from django.conf import settings
from django.utils.timezone import now
from django.db.models import (
    Q,
    F,
    Count,
    CharField,
    DecimalField,
    Value,
    Sum,
    Avg,
    Min,
    Max,
)
from django.utils.translation import gettext as _
from django.core import signing
from django.db.models import Q, F, Count, Sum, Case, When, BooleanField, IntegerField
from django.utils import timezone

# EXTRA MODULES
import sweetify
from notifications.signals import notify
from notifications.models import Notification

# PROJECT MODULES
from offers.forms import (
    OfferAdminForm,
    OfferForm,
    CandidatureStatusEditForm,
    CandidatureUpdateForm,
)
from offers.models import Tags, Offers, Candidatures
from offers.utils import (
    get_pk_from_a_slug,
    send_new_offer_notification,
    get_status_name,
    send_notification_of_candidacy_status,
    OFFER_STATUS,
    POST_STATUS,
)
from core.utils import success_message, warning_message, get_form_errors
from users.models import UserRules, UserGroupPolicies
from users.forms import FormDelete
from jobboard.utils import *

# GLOBAL VARIABLES
app_title = _("Ofertas")
offer_title = _("Ofertas")
offer_desc = _("Ofertas")
offer_create_title = _("Publicar")
offer_update_title = _("Editar")
offer_detail_title = _("Detalle")
publication_title = _("Publicaciones")
publication_desc = _("Listado de mis publicaciones")
candidature_title = _("Candidaturas")
candidature_desc = _("Postulaciones a ofertas laborales")
candidature_offer_title = _("Candidaturas")
candidature_offer_desc = _("Postulaciones de la oferta")


# OFFERS
class OfferList(LoginRequiredMixin, generic.ListView):
    login_url = "/login"
    model = Offers
    template_name = "offers/offer_list.html"
    paginate_by = 10

    def get_queryset(self):
        return Offers.objects.all().order_by("id")

    def get_context_data(self, **kwargs):
        context = super(OfferList, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = offer_title
        context["description_view"] = offer_desc
        return context


class OfferDetail(LoginRequiredMixin, generic.DetailView):
    login_url = "/login"
    model = Offers
    template_name = "offers/offer_detail.html"

    def get_object(self):
        str_pk = get_pk_from_a_slug(self)

        return self.model.objects.get(pk=str_pk)

    def get_context_data(self, **kwargs):
        context = super(OfferDetail, self).get_context_data(**kwargs)
        offer = self.get_object()
        offers_cache = (
            Offers.objects.exclude(id=offer.id)
            .filter(
                deleted_at=None,
            )
            .order_by("-created_at", "updated_at")
        )

        offers = offers_cache.filter(Q(tags__in=offer.get_tags()))

        if not offers:
            offers = offers_cache.filter(deleted_at=None)

        offers = offers[:2]

        user = self.request.user

        candidatures = Candidatures.objects.filter(offer=offer.id, deleted_at=None)

        allowed_to_apply = UserRules.objects.filter(user=user, usergroup__code="GRA")
        allowed_to_edit = UserRules.objects.filter(
            user=user,
            user__offer_user=offer.id,
            usergroup__usergroup_policy__app__name="offers_app:offer_edit",
        )
        allowed_to_candidates = UserRules.objects.filter(
            Q(
                user=user,
                usergroup__code="MOD",
                usergroup__usergroup_policy__app__name="offers_app:candidature_list",
            )
            | Q(user=user, usergroup__code="COM", user__offer_user=offer.id),
        )

        candidature = candidatures.filter(candidate=user)

        context["allowed_to_apply"] = allowed_to_apply
        context["allowed_to_edit"] = allowed_to_edit
        context["allowed_to_candidates"] = allowed_to_candidates
        context["similar_offers"] = offers
        context["candidature"] = candidature and candidature.first()
        context["candidatures"] = candidatures
        context["app_title"] = app_title
        context["title_view"] = offer_detail_title
        context["description_view"] = offer_desc
        context["in_offer"] = True
        context["in_offer_detail"] = True
        return context


class OfferModalCreate(LoginRequiredMixin, generic.CreateView):
    login_url = "/login"
    model = Offers
    form_class = OfferAdminForm
    template_name = "offers/offer_create_modal.html"

    def get_success_url(self):
        success_message(self.request)
        return reverse_lazy("offers_app:offer_list")

    def get_context_data(self, **kwargs):
        context = super(OfferModalCreate, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        form.instance.title = str(form.instance.title).upper()
        return super().form_valid(form)

    def form_invalid(self, form, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx["form"] = form

        msg_error = get_form_errors(form)
        warning_message(self.request, msg=msg_error)
        return HttpResponseRedirect(reverse_lazy("offers_app:offer_list"))


class OfferEditModal(LoginRequiredMixin, generic.UpdateView):
    login_url = "/login"
    model = Offers
    form_class = OfferAdminForm
    template_name = "offers/offer_update_modal.html"

    def get_success_url(self):
        success_message(self.request, msg="Oferta actualizada satisfactoriamente")
        return reverse_lazy("offers_app:offer_list")

    def get_context_data(self, **kwargs):
        context = super(OfferEditModal, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = offer_title
        context["description_view"] = offer_desc
        return context

    def form_valid(self, form):
        form.instance.updated_at = timezone.now()
        form.instance.title = str(form.instance.title).upper()
        return super().form_valid(form)

    def form_invalid(self, form, **kwargs):
        ctx = self.get_context_data(**kwargs)
        ctx["form"] = form

        msg_error = get_form_errors(form)
        warning_message(self.request, msg=msg_error)
        return HttpResponseRedirect(reverse_lazy("offers_app:offer_list"))


class OfferDeleteModal(LoginRequiredMixin, generic.UpdateView):
    login_url = "/login"
    model = Offers
    form_class = FormDelete
    template_name = "offers/offer_delete_modal.html"

    def get_object(self):
        pk = get_pk_from_a_slug(self)
        return self.model.objects.get(pk=pk)

    def get_success_url(self):
        success_message(self.request, msg="Oferta eliminada satisfactoriamente")
        offer = self.get_object()
        Candidatures.objects.filter(offer=offer, status="1").update(
            status="2", updated_at=timezone.now()
        )
        if self.request.user.is_staff:
            return reverse_lazy("offers_app:offer_list")
        return reverse_lazy(
            "offers_app:mypublications", args=[self.request.user.username]
        )

    def get_context_data(self, **kwargs):
        context = super(OfferDeleteModal, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = offer_title
        context["description_view"] = offer_desc
        return context

    def form_valid(self, form):
        form.instance.deleted_at = timezone.now()
        return super().form_valid(form)


class OfferFinishModal(LoginRequiredMixin, generic.UpdateView):
    login_url = "/login"
    model = Offers
    form_class = FormDelete
    template_name = "offers/offer_finish_modal.html"

    def get_object(self):
        pk = get_pk_from_a_slug(self)
        return self.model.objects.get(pk=pk)

    def get_success_url(self):
        success_message(self.request, msg="Oferta finalizada satisfactoriamente")
        offer = self.get_object()
        Candidatures.objects.filter(offer=offer, status="1").update(
            status="2", updated_at=timezone.now()
        )
        return reverse_lazy(
            "offers_app:mypublications", args=[self.request.user.username]
        )

    def get_context_data(self, **kwargs):
        context = super(OfferFinishModal, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = offer_title
        context["description_view"] = offer_desc
        return context

    def form_valid(self, form):
        p_status = self.request.GET.get("status", False)
        if not p_status == "true":
            warning_message(self.request, msg="Esta acción no ha podido completarse")
            return HttpResponseRedirect(
                reverse_lazy(
                    "offers_app:mypublications", args=[self.request.user.username]
                )
            )
        form.instance.status = True
        form.instance.updated_at = timezone.now()
        return super().form_valid(form)


class BiddingPanel(LoginRequiredMixin, generic.ListView):
    login_url = "/login"
    model = Offers
    template_name = "offers/bidding_panel.html"
    paginate_by = 10

    def get_queryset(self):
        search = self.request.GET.get("search", "true")
        order = self.request.GET.get("order", "-created_at")
        return self.model.objects.search(text=search, order=order).filter(
            deleted_at=None, status=False
        )

    def get_context_data(self, **kwargs):

src/offers/templates/offers/offer_create_modal.html
{% load static %}

<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <form method="POST" action="{% url 'offers_app:offer_modal_add' %}" id="form">
        {% include 'partials/_form_create_modal.html' %}
      </form>
    </div>
  </div>

src/offers/templates/offers/offer_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load format_numbers %}

{% block title %}
<title>{{app_title}} | {{title_view}}</title>
{% endblock title %}

{% block contentfluid %}
<section class="layout-section">
    {% include 'partials/_aside.html' %}
    <div class="main-section">
        <div class="container">
            <div class="card p-4 rounded-4">
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3">
                        <div class="d-flex flex-column gap-3">
                            {% include 'partials/_gettags.html' %}
                            <h4 class="fs-4 m-0">
                                <span class="d-flex gap-1 align-items-center">
                                    {{ object.title }}
                                    {% if allowed_to_edit or request.user.is_staff  %} 
                                    <a href="{% url 'offers_app:offer_edit' object.slug %}" class="btn btn-link btn-sm rounded-circle" role="button">
                                        {% include 'partials/icon_element/_pencil_icon.html' %}
                                    </a>
                                    {% endif %}
                                </span>
                            </h4>
                        </div>
                        <div>
                            <span class="text-black-50">{{ object.created_at }}</span>
                        </div>
                    </div>
                    <div class="row gap-1">
                        <div class="col-12 d-flex gap-2">
                            {% include 'partials/icon_element/_location_icon.html' %}
                            <span class="text-black-50">{{ object.city }}, {{ object.city.district }}</span>
                        </div>
                        <div class="col-12 d-flex gap-2">
                            {% include 'partials/icon_element/_table_icon.html' %}
                            <span class="text-black-50">Modalidad: {{ object.modality }}</span>
                        </div>
                        <div class="col-12 d-flex gap-2">
                            {% include 'partials/icon_element/_people_icon.html' %}
                            <span class="text-black-50">
                                {% if object.vacancies == 1 %}
                                Una vacante
                                {% else %}
                                {{ object.vacancies }} vacantes
                                {% endif %}
                            </span>
                        </div>
                        <div class="col-12 d-flex gap-2">
                            {% include 'partials/icon_element/_suitcase_icon.html' %}
                            <span class="text-black-50">Contrato a {{ object.conttype }}</span>
                        </div>
                        <div class="col-12 d-flex gap-2">
                            {% include 'partials/icon_element/_time_icon.html' %}
                            <span class="text-black-50">{{ object.workday }}</span>
                        </div>
                        <div class="col-12 d-flex gap-2">
                            {% include 'partials/icon_element/_calendar_icon.html' %}
                            <span class="text-black-50">Fecha de contratación: {{ object.hiring_date }}</span>
                        </div>
                        <div class="col-12 d-flex gap-2">
                            {% include 'partials/icon_element/_dolar_icon.html' %}
                            <span class="text-black-50">{{ object.currency }} {{ object.salary|currency_format }} {{ object.payperiod }}</span>
                        </div>
                    </div>
                    <h6 class="mt-4 fw-bold">Descripción</h6>
                    <div>{{ object.description|linebreaks }}</div>
                    <h6 class="mt-4 fw-bold">Requisitos</h6>
                    {% if object.get_requirements %}
                        {% for requirement in object.get_requirements %}
                            <p>{{requirement}}: Sí</p>
                        {% endfor %}
                    {% else %}
                        <p>No especifica</p>
                    {% endif %}
                    {% if allowed_to_candidates or request.user.is_staff %}
                    <h6 class="mt-4 fw-bold">Candidatos</h6>
                        {% if candidatures %}
                        <p>
                            {% if candidatures|length == 1 %}
                            Un candidato ha 
                            {% else %}
                            {{ candidatures|length }} candidatos han
                            {% endif %}
                            aplicado a esta oferta
                            <br>
                            <a href="{% url 'offers_app:candidature_list' object.slug %}" class="link-orange" role="button">
                                Ver todos los candidatos
                            </a>
                        </p>
                        {% else %}
                        <p class="text-muted fst-italic">Sin candidatos</p>
                        {% endif %}
                    {% endif %}

                    {% if object.deleted_at %}
                    <div class="alert alert-danger" role="alert">
                        Oferta no disponible
                    </div>
                    {% elif allowed_to_apply or request.user.is_staff %}
                        {% if not candidature and not object.status %}
                            <button
                                type="button"
                                class="btn btn-primary rounded-pill px-4"
                                name="createButtons"
                                id="{% url 'offers_app:candidature_status_edit' object.slug request.user.username %}?path=mycandidacies&status=1"
                            >
                                <span class="">Aplicar</span>
                            </button>
                        {% elif candidature %}
                            {% if candidature.status == '1' %}
                            <div class="alert alert-warning" role="alert">
                                Has {{ candidature.get_status_display }} a esta oferta
                            </div>
                            {% elif candidature.status == '2' %}
                            <div class="alert alert-warning" role="alert">
                                Has {{ candidature.get_status_display }} la postulación a esta oferta
                            </div>
                            {% elif candidature.status == '3' %}
                            <div class="alert alert-danger" role="alert">
                                ¡Lo sentimos!
                                <br>
                                Desafortunadamente fuiste {{ candidature.get_status_display }} y ya no podrás aplicar de nuevo
                                <br>
                                <span class="text-decoration-underline" id="goToSimilarOffers" type="button" role="button">
                                    ¡Pero no te preocupes. Revisa las "ofertas similares" y aplica a las que más te gusten!
                                </span>
                            </div>
                            {% elif candidature.status == '4' %}
                            <div class="alert alert-success" role="alert">
                                ¡Bien hecho, estamos en la siguiente fase!
                                <br>
                                Has sido {{ candidature.get_status_display }} en esta oferta y falta poco para que seas contratado
                            </div>
                            {% elif candidature.status == '5' %}
                            <div class="alert alert-success" role="alert">
                                ¡Enhorabuena, fuiste {{ candidature.get_status_display }}!
                            </div>
                            {% endif %}
                            {% if candidature.status == '1' or candidature.status == '4' %}
                            <a 
                                href="{% url 'offers_app:mycandidacies' request.user.username %}"
                                class="link-orange"
                            >
                                Ver postulaciones
                            </a>
                            {% endif %}
                        {% elif object.status %}
                            <div class="alert alert-warning" role="alert">
                                Esta oferta ya finalizó
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% comment %} <article class="footer position-relative" style="z-index: 2;">
    {% include 'partials/_footer.html' %}
</article>  {% endcomment %}

{% endblock contentfluid %}

src/offers/templates/offers/offer_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load crypto_url %}

{% block title %}
<title>{{app_title}} | {{title_view}}</title>
{% endblock title %}

{% block contentfluid %}    
<section class="layout-section">
  {% include 'partials/_aside.html' %}
  <div class="main-section">
    <div class="container">
      {% include 'partials/_display.html' %}
      <div class="row gy-3 mt-3">
        <div class="col-12">
            <button
            type="button"
            class="btn btn-primary btn-center btn-compact"
            name="createButtons"
            id="{% url 'offers_app:offer_modal_add' %}"
          >
            <i class="lni lni-plus"></i>
            <span class="ms-2">Crear</span>
          </button>
        </div>
        <div class="col-12">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th>Título</th>
                <th>Empresa</th>
                <th>Salario</th>
                <th>Modalidad</th>
                <th>Estado</th>
                <th>Ver</th>
                <th>Editar</th>
                <th>Eliminar</th>
              </tr>
            </thead>
            <tbody>
              {% for row in object_list %}
              <tr>
                <td scope="row" {% if row.deleted_at %}class="text-decoration-line-through"{% endif %}>{{row.id}}</td>
                <td {% if row.deleted_at %}class="text-decoration-line-through"{% endif %}>{{row.title}}</td>
                <td {% if row.deleted_at %}class="text-decoration-line-through"{% endif %}>{{row.user.userprofile.company_profile}}</td>
                <td {% if row.deleted_at %}class="text-decoration-line-through"{% endif %}>{{row.currency}} {{row.salary}} {{row.payperiod}}</td>
                <td {% if row.deleted_at %}class="text-decoration-line-through"{% endif %}>{{row.modality}}</td>
                <td {% if row.deleted_at %}class="text-decoration-line-through"{% endif %}>
                  {% if row.deleted_at %} 
                  Eliminado el {{row.deleted_at}}
                  {% elif row.updated_at %} 
                  Actualizado el {{row.updated_at}}
                  {% else %}
                  Creado el {{row.created_at}}
                  {% endif %}
                </td>
                <td>
                  <a
                    href="{% url 'offers_app:offer_detail' row.slug %}"
                    role="button"
                    class="btn btn-outline-secondary btn-center btn-compact"
                  >
                    <i class="lni lni-eye"></i>
                  </a>
                </td>
                <td>
                  {% if not row.deleted_at %}
                  <button
                    type="button"
                    class="btn btn-outline-primary btn-center btn-compact"
                    name="editButtons"
                    id="{% url 'offers_app:offer_edit' row.id %}"
                  >
                    <i class="lni lni-pencil"></i>
                  </button>
                  {% endif %}
                </td>
                <td>
                  {% if not row.deleted_at %}
                  <button
                    type="button"
                    class="btn btn-outline-danger btn-center btn-compact"
                    name="deleteButtons"
                    id="{% url 'offers_app:offer_delete' row.slug %}"
                  >
                    <i class="lni lni-trash-can"></i>
                  </button>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% if is_paginated %}
        {% include 'partials/_pagination_sm.html' %}
        {% endif %}
      </div>
    </div>
  </div>
</section>

{% endblock contentfluid %}

src/offers/templates/offers/offer_update_modal.html
{% load static %}

<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <form
      method="POST"
      action="{% url 'offers_app:offer_edit' object.id %}"
      id="form"
    >
      {% include 'partials/_form_update_modal.html' %}
    </form>
  </div>
</div>