src/home/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from .views import *

app_name = "home_app"

urlpatterns = [
    path("", HomeView.as_view(), name="home_page"),
    path("help", HelpView.as_view(), name="help"),
]

src/jobboard/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("home.urls")),
    path("", include("config.urls")),
    path("offer/", include("offers.urls")),
    path("reports/", include("reports.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/offers/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from .views import *

app_name = "offers_app"

urlpatterns = [
    # OFFERS
    path("list", OfferList.as_view(), name="offer_list"),
    path("panel", BiddingPanel.as_view(), name="bidding_panel"),
    path("publish", PublicationCreate.as_view(), name="offer_add"),
    path("update/<slug:slug>", PublicationEdit.as_view(), name="offer_edit"),
    path("detail/<slug:slug>", OfferDetail.as_view(), name="offer_detail"),
    path("modal/create", OfferModalCreate.as_view(), name="offer_modal_add"),
    path("modal/edit/<int:pk>", OfferEditModal.as_view(), name="offer_edit"),
    path("modal/delete/<slug:slug>", OfferDeleteModal.as_view(), name="offer_delete"),
    path("modal/finish/<slug:slug>", OfferFinishModal.as_view(), name="offer_finish"),
    path(
        "<str:username>/publications", PublicationList.as_view(), name="mypublications"
    ),
    # CANDIDATURES
    path("candidatures/list", CandidaturesList.as_view(), name="candidature_list"),
    path(
        "<slug:slug>/candidatures/list",
        CandidaturesByOfferList.as_view(),
        name="candidature_list",
    ),
    path(
        "candidatures/<str:username>/list",
        MyCandidacies.as_view(),
        name="mycandidacies",
    ),
    path(
        "<str:slug>/candidatures/save/<str:username>",
        CandidatureStatusEdit.as_view(),
        name="candidature_status_edit",
    ),
    path(
        "candidatures/modal/edit/<int:pk>",
        CandidatureEditModal.as_view(),
        name="candidature_edit",
    ),
    path(
        "candidatures/modal/delete/<int:pk>",
        CandidatureDeleteModal.as_view(),
        name="candidature_delete",
    ),
]

src/reports/urls.py
# DJANGO MODULES
from django.contrib import admin
from django.urls import path

# PROJECT MODULES
from reports.views import *

app_name = "reports_app"

urlpatterns = [
    path("home", ReportsHome.as_view(), name="reports_home"),
    path("users", UserReport.as_view(), name="user_report"),
    path("offers", OfferReport.as_view(), name="offer_report"),
]

src/reports/models.py
from django.db import models

# Create your models here.

src/reports/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.views import generic
from django.db.models import (
    Q,
    F,
    Count,
    CharField,
    DecimalField,
    Value,
    Sum,
    Avg,
    Min,
    Max,
)

from offers.models import Offers
from users.models import UserGroups

# GLOBAL VARIABLES
app_title = _("Reportes")
reports_page_title = _("Panel de reportes")
reports_page_desc = _("Reportes de usuarios y ofertas")
user_report_title = _("Usuarios")
user_report_desc = _("Panel de reportes de los usuarios 'empresa' y 'egresado'")
offer_report_title = _("Ofertas")
offer_report_desc = _("Listado de las ofertas publicadas")


# Create your views here.
class ReportsHome(LoginRequiredMixin, generic.TemplateView):
    login_url = "/login"
    template_name = "reports/reports_home.html"

    def get_context_data(self, **kwargs):
        context = super(ReportsHome, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = reports_page_title
        context["description_view"] = reports_page_desc
        context["reports"] = True
        return context


class UserReport(LoginRequiredMixin, generic.ListView):
    login_url = "/login"
    model = User
    template_name = "reports/user_report.html"
    paginate_by = 10

    def get_queryset(self):
        usergroup = self.request.GET.get("usergroup", "")
        obj = self.model.objects.all().order_by("id")
        if usergroup:
            obj = obj.filter(rule_user__usergroup__code__in=[usergroup])
        return obj

    def get_context_data(self, **kwargs):
        context = super(UserReport, self).get_context_data(**kwargs)
        usergroup = self.request.GET.get("usergroup", "")

        title_view = user_report_title
        description_view = user_report_desc

        if usergroup:
            usergroup_obj = UserGroups.objects.get(code=usergroup)
            title_view = usergroup_obj.group_name
            description_view = f"Listado de los usuarios '{title_view}'"

        context["app_title"] = app_title
        context["title_view"] = title_view.capitalize()
        context["description_view"] = description_view
        context["reports"] = True
        return context


class OfferReport(LoginRequiredMixin, generic.ListView):
    login_url = "/login"
    model = Offers
    template_name = "reports/offer_report.html"
    paginate_by = 10

    def get_queryset(self):
        tag = self.request.GET.get("tag", "")
        order = self.request.GET.get("order", "-created_at")

        obj = self.model.objects.all()
        if "count" in order:
            obj = obj.annotate(count=Count(F("candidature_offer")))
        if "ctags" in order:
            obj = obj.annotate(ctags=Count(F("tags")))
        if tag:
            obj = obj.filter(tags__name__in=[tag])
        return obj.order_by(order)

    def get_context_data(self, **kwargs):
        context = super(OfferReport, self).get_context_data(**kwargs)
        context["app_title"] = app_title
        context["title_view"] = offer_report_title
        context["description_view"] = offer_report_desc
        context["reports"] = True
        return context

src/reports/templates/reports/offer_report.html
{% extends 'core/base.html' %}{% load static %} {% block title %}
<title>{{app_title}} | {{title_view}}</title>
{% endblock title %} {% block contentfluid %}
<section class="layout-section">
  {% include 'partials/_aside.html' %}
  <div class="main-section">
    <div class="container">
      {% include 'partials/_display.html' %}
      <div class="row gy-3 mt-3">
        
        <div class="col-12">
          <table class="table">
            <thead>
              <tr>
                <th>
                  {% if '-' in request.GET.order %}
                  <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=title">
                    Ofertas
                  </a>
                  {% else %}
                  <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=-title">
                    Ofertas
                  </a>
                  {% endif %}
                </th>
                <th>
                  <div class="d-flex align-items-center gap-1">
                    {% if '-' in request.GET.order %}
                    <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=ctags">
                      Etiquetas
                    </a>
                    {% else %}
                    <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=-ctags">
                      Etiquetas
                    </a>
                    {% endif %}
                    {% if request.GET.tag %}
                    <a href="?tag=" class="btn btn-outline-danger btn-sm border-0">
                      <span class="d-flex justify-content-center align-items-center">
                        <i class="lni lni-trash-can"></i>
                      </span>
                    </a>
                    {% endif %}
                  </div>
                </th>
                <th>
                  {% if '-' in request.GET.order %}
                  <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=count">
                    N° candidatos
                  </a>
                  {% else %}
                  <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=-count">
                    N° candidatos
                  </a>
                  {% endif %}
                </th>
                <th>
                  {% if '-' in request.GET.order %}
                  <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=created_at">
                    Fecha
                  </a>
                  {% else %}
                  <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=-created_at">
                    Fecha
                  </a>
                  {% endif %}
                </th>
                <th>
                  {% if '-' in request.GET.order %}
                  <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=status">
                    Estado
                  </a>
                  {% else %}
                  <a class="text-decoration-none text-black" href="?tag={{request.GET.tag}}&order=-status">
                    Estado
                  </a>
                  {% endif %}
                </th>
                <th>
                  Detalle
                </th>
              </tr>
            </thead>
            <tbody>
              {% for row in object_list %}
              <tr>
                <td>{{ row.title }}</td>
                <td>
                  {% with row as object %}
                  {% if object.tags.count %}
                  {% include 'partials/_gettags.html' %}
                  {% else %}
                  Sin etiquetas
                  {% endif %}
                  {% endwith %}
                </td>
                <td>
                  <a href="{% url 'offers_app:candidature_list' row.slug %}" class="link-orange" role="button">
                    {% if row.candidature_offer.count == 0 %}
                    Sin candidatos
                    {% elif row.candidature_offer.count == 1 %}
                    Un candidato
                    {% else %}
                    {{ row.candidature_offer.count }} candidatos
                    {% endif %}
                  </a>
                </td>
                <td>{{ row.created_at }}</td>
                <td>
                  {% if row.status %}
                  Finalizada
                  {% else %}
                  Activa
                  {% endif %}
                </td>
                <td>
                  <a
                    href="{% url 'offers_app:offer_detail' row.slug %}"
                    class="btn btn-outline-secondary btn-center btn-compact"
                  >
                    <i class="lni lni-eye"></i>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      {% if is_paginated %} {% include 'partials/_pagination_sm.html' %} {% endif %}
    </div>
  </div>
</section>

{% endblock contentfluid %}

src/reports/templates/reports/reports_home.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
<title>{{app_title}} | {{title_view}}</title>
{% endblock title %}

{% block contentfluid %}
<section class="layout-section">
  {% include 'partials/_aside.html' %}
  <div class="main-section">
    <div class="container">
      {% include 'partials/_display.html' %}
      <div class="row gy-3 mt-3">
        <div class="col-12">
          <div class="d-flex gap-2">
            <div class="card bid-letter position-relative" style="max-width: 25rem;">
              <div class="card-body">
                <div class="card-head">
                  <span class="c-head-icon">
                    <i class="lni lni-users"></i>
                  </span>
                  <div class="head-title">Reporte de usuarios</div>
                </div>
                <p>Revisa los registros de los usuarios "empresa" o "egresado"</p>
              </div>
              <a class="stretched-link" href="{% url 'reports_app:user_report' %}"></a>
            </div>

            <div class="card bid-letter position-relative" style="max-width: 25rem;">
              <div class="card-body">
                <div class="card-head">
                  <span class="c-head-icon">
                    <i class="lni lni-offer"></i>
                  </span>
                  <div class="head-title">Reporte de ofertas</div>
                </div>
                <p>Revisa las ofertas que han sido publicadas</p>
              </div>
              <a class="stretched-link" href="{% url 'reports_app:offer_report' %}"></a>
            </div>
          </div>
        </div>
      </div>
      {% if is_paginated %}
      {% include 'partials/_pagination_sm.html' %}
      {% endif %}
    </div>
  </div>
</section>

{% endblock contentfluid %}

src/reports/templates/reports/user_report.html
{% extends 'core/base.html' %} {% load static %} {% block title %}
<title>{{app_title}} | {{title_view}}</title>
{% endblock title %} {% block contentfluid %}
<section class="layout-section">
  {% include 'partials/_aside.html' %}
  <div class="main-section">
    <div class="container">
      {% include 'partials/_display.html' %}
      <div class="row gy-3 mt-3">
        <div class="col-12">
          {% if request.GET.usergroup == 'GRA' %}
          {% include 'partials/_graduate_table.html' %}
          {% elif request.GET.usergroup == 'COM' %}
          {% include 'partials/_company_table.html' %}
          {% else %}
          <div class="d-flex gap-2">
            <div class="card bid-letter position-relative">
              <div class="card-body">
                <div class="card-head">
                  <span class="c-head-icon"
                    ><i class="lni lni-apartment"></i
                  ></span>
                  <div class="head-title">Empresas</div>
                </div>
                <p>Revisa los registros de las empresas</p>
              </div>
              <a class="stretched-link" href="{% url 'reports_app:user_report' %}?usergroup=COM"></a>
            </div>
            <div class="card bid-letter position-relative">
              <div class="card-body">
                <div class="card-head">
                  <span class="c-head-icon"
                    ><i class="lni lni-graduation"></i
                  ></span>
                  <div class="head-title">Egresados</div>
                </div>
                <p>Revisa los registros de los egresados</p>
              </div>
              <a class="stretched-link" href="{% url 'reports_app:user_report' %}?usergroup=GRA"></a>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
      {% if request.GET.usergroup == 'GRA' or request.GET.usergroup == 'COM'%}
        {% if is_paginated %}
        {% include 'partials/_pagination_sm.html' %}
        {% endif %}
      {% endif %}
    </div>
  </div>
</section>

{% endblock contentfluid %}